load("//:defs.bzl", "hightide_design")

hightide_design(
    name = "floonoc",
    top = "floonoc_mesh_top",
    platform = "nangate45",
    verilog_files = ["//designs/src/floonoc:rtl"],
    sources = {
        "SDC_FILE": [":constraint.sdc"],
        "FOOTPRINT_TCL": [":io.tcl"],
    },
    stage_data = {"synth": ["//designs/src/floonoc:rtl_data"]},
    arguments = {
        "SYNTH_HDL_FRONTEND": "slang",
        "VERILOG_INCLUDE_DIRS": "external/+_repo_rules+pulp_common_cells_src/include external/+_repo_rules+pulp_apb_src/include external/+_repo_rules+pulp_axi_src/include external/+_repo_rules+pulp_axi_stream_src/include external/+_repo_rules+pulp_obi_src/include external/+_repo_rules+pulp_register_interface_src/include external/+_repo_rules+floonoc_src/hw/include",
        "VERILOG_DEFINES": "-D VERILATOR",
        "DIE_AREA": "0 0 900 900",
        "CORE_AREA": "5 5 895 895",
        "TNS_END_PERCENT": "100",
    },
)
